modified:   cmd/poetry.lock 	modified:   cmd/pyproject.toml 	modified:   cmd/resources/docker/linux.Dockerfile 	modified:   cmd/resources/docker/windows.Dockerfile 	modified:   cmd/src/ryujinxkit_cmd/constants/configs.py 	modified:   cmd/src/ryujinxkit_cmd/enums.py 	modified:   cmd/src/ryujinxkit_cmd/functions/entrypoint.py 	modified:   cmd/src/ryujinxkit_cmd/functions/source.py 	modified:   cmd/src/ryujinxkit_cmd/session.py 	deleted:    scripts/build-exe.ps1 	modified:   server/pyproject.toml 	modified:   server/resources/docker/Dockerfile 	modified:   server/src/ryujinxkit_server/constants/server.py

diff --git a/server/resources/docker/Dockerfile b/server/resources/docker/Dockerfile
--- a/server/resources/docker/Dockerfile
+++ b/server/resources/docker/Dockerfile
@@ -1,27 +1,12 @@
-# =============================================================================
-
 FROM python:3.13-bullseye AS poetry
 WORKDIR /workdir
-
 RUN pip install poetry
 
-# -----------------------------------------------------------------------------
-
 FROM poetry
-ENV RYUJINXKIT_CONTENT=temp/data
+ARG content_location
+RUN test -n "${content_location}" || (echo "Required argument \${content_location}." && exit 1)
+ENV RYUJINXKIT_CONTENT=${content_location}
 EXPOSE 8000
-
 COPY . .
-
 RUN python -m poetry install
-
-ENTRYPOINT [ \
-    "poetry", \
-    "run" , \
-    "gunicorn", \
-    "-b", \
-    "0.0.0.0:8000", \
-    "ryujinxkit_server.constants.server:APP" \
-    ]
-
-# =============================================================================
+ENTRYPOINT [ "python", "-m", "poetry", "run", "gunicorn", "-b", "0.0.0.0:8000", "ryujinxkit_server.constants.server:APP" ]
